"""
GDPR Shift-Left MCP Server — Disclaimer Utilities

Every response produced by this MCP server MUST include the legal disclaimer.
This module provides the canonical disclaimer text and helpers that append it.
"""

LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "**Disclaimer:** This output is generated by an automated compliance assistance "
    "tool and does **not** constitute legal advice. It is provided for informational "
    "and educational purposes only. Organizations should consult qualified legal "
    "counsel and their Data Protection Officer (DPO) before making compliance "
    "decisions. The authors and contributors of this tool accept no liability for "
    "actions taken based on its output."
)

GDPR_CITATION_FOOTER = (
    "\n\n*Source: Regulation (EU) 2016/679 of the European Parliament and of the "
    "Council (General Data Protection Regulation). Supplementary guidance from "
    "EDPB guidelines and ICO resources is referenced where applicable.*"
)


def append_disclaimer(text: str) -> str:
    """Append the legal disclaimer to any tool output."""
    return text + GDPR_CITATION_FOOTER + LEGAL_DISCLAIMER


def get_disclaimer() -> str:
    """Return the standalone legal disclaimer."""
    return LEGAL_DISCLAIMER
